controller_manager_ns: controller_manager
controller_list:
  - name: dual_ur5_arm/left_arm_joint_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint

  - name: dual_ur5_arm/right_arm_joint_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint

  - name: dual_ur5_arm/left_gripper_controller
    action_ns: follow_joint_trajectory #gripper_cmd #  gripper_cmd #follow_joint_trajectory # 
    type: FollowJointTrajectory #GripperCommand #GripperCommand # FollowJointTrajectory # FollowJointTrajectory
    joints:
      - left_rh_l1
      - left_rh_l2
      - left_rh_p12_rn
      - left_rh_r2
    
  - name: dual_ur5_arm/right_gripper_controller
    action_ns: follow_joint_trajectory #gripper_cmd #  gripper_cmd #follow_joint_trajectory # 
    type: FollowJointTrajectory #GripperCommand #GripperCommand # FollowJointTrajectory # FollowJointTrajectory
    joints:
      - right_rh_l1
      - right_rh_l2
      - right_rh_p12_rn
      - right_rh_r2




