left_arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin #kdl_kinematics_plugin/KDLKinematicsPlugin
  solve_type: Distance
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
#  kinematics_solver_attempts: 3
right_arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin #kdl_kinematics_plugin/KDLKinematicsPlugin
  solve_type: Distance
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
#  kinematics_solver_attempts: 3
dual_arms:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin #kdl_kinematics_plugin/KDLKinematicsPlugin
  solve_type: Distance
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
#  kinematics_solver_attempts: 3
