# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: left_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - left_shoulder_pan_joint
    - left_shoulder_lift_joint
    - left_elbow_joint
    - left_wrist_1_joint
    - left_wrist_2_joint
    - left_wrist_3_joint
    - left_rh_l1
    - left_rh_l2
    - left_rh_p12_rn
    - left_rh_r2
    - right_shoulder_pan_joint
    - right_shoulder_lift_joint
    - right_elbow_joint
    - right_wrist_1_joint
    - right_wrist_2_joint
    - right_wrist_3_joint
    - right_rh_l1
    - right_rh_l2
    - right_rh_p12_rn
    - right_rh_r2
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []