controller_list:
  - name: fake_left_arm_controller
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
  - name: fake_right_arm_controller
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
  - name: fake_left_gripper_controller
    joints:
      - left_rh_l1
      - left_rh_l2
      - left_rh_p12_rn
      - left_rh_r2
  - name: fake_right_gripper_controller
    joints:
      - right_rh_l1
      - right_rh_l2
      - right_rh_p12_rn
      - right_rh_r2
  - name: fake_dual_arms_controller
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
      - left_rh_l1
      - left_rh_l2
      - left_rh_p12_rn
      - left_rh_r2
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
      - right_rh_l1
      - right_rh_l2
      - right_rh_p12_rn
      - right_rh_r2